[theme]
primaryColor = "#000000"             
backgroundColor = "#DEE5D4"          
secondaryBackgroundColor = "#FEF9F2" 
textColor = "#000000"                
font="monospace"


#DEE5D4 (EDE8DC) (FEF9F2)
#D1E9F6